export const ProductData = [
  {
    id: 1,
    title: "Shoes",
    url: "https://dms.deckers.com/hoka/image/upload/f_auto,q_auto,dpr_auto/b_rgb:f7f7f9/w_414/v1718901379/1147790-SRYB_1.png?_s=RAABAB0",
    name: "Shoes",
    category: "Shoes",
    seller: "AMZ",
    price: 1999,
  },
  {
    id: 2,
    title: "Digital Watch",
    url: "https://thumbs.dreamstime.com/b/horizontal-website-screen-responsive-web-design-smart-watch-mock-up-banner-layout-marketing-landing-page-vector-illustration-145020366.jpg",
    name: "Digital Watch",
    category: "DigitalWatch",
    seller: "AMZ",
    price: 2599,
  },
  {
    id: 3,
    title: "Laptop",
    url: "https://media.istockphoto.com/id/1157329704/photo/flying-tablet-laptop-and-mobile-phone-showing-online-shop-website.jpg?s=612x612&w=0&k=20&c=jdX1yWsNUiTsvHvC0y0OIM-OOFjqQwlcUy_x114HtLQ=",
    name: "Laptop",
    category: "Laptop",
    seller: "AMZ",
    price: 29999,
  },
  {
    id: 4,
    title: "Security Camera",
    url: "https://www.shutterstock.com/image-vector/3d-vector-white-safety-security-260nw-2310117983.jpg",
    name: "Security Camera",
    category: "SecurityCamera",
    seller: "AMZ",
    price: 7999,
  },
  {
    id: 5,
    title: "Watch",
    url: "https://w3layouts.com/wp-content/uploads/2015/07/watches.jpg",
    name: "Watch",
    category: "Watch",
    seller: "AMZ",
    price: 13999,
  },
  {
    id: 6,
    url: "https://149842030.v2.pressablecdn.com/wp-content/uploads/2018/08/2-mugs.png",
    name: "Mug",
    category: "Mug",
    seller: "AMZ",
    price: 3599,
  },
  {
    id: 7,
    url: "https://miro.medium.com/v2/resize:fit:1400/1*pmDkVRE9h7szMoSY_5tsbg.jpeg",
    name: "Mobile",
    category: "Mobile",
    seller: "AMZ",
    price: 19999,
  },
  {
    id: 8,
    url: "https://thumbs.dreamstime.com/z/mobile-phone-charger-isolated-white-background-43224295.jpg",
    name: "Mobile Charger",
    category: "Mobile Charger Black Color",
    seller: "AMZ",
    price: 599,
  },
  {
    id: 9,
    url: "https://c8.alamy.com/comp/JEKRH5/black-cell-phone-charger-cord-on-a-white-surface-cell-phone-charger-JEKRH5.jpg",
    name: "Mobile Charger",
    category: "Mobile Charger White Color",
    seller: "AMZ",
    price: 599,
  },
  {
    id: 10,
    url: "https://www.whatmobile.com.pk/control/news/assets/21102023/2a8d27a92c2b7b7b2bc187127e82202e.jpg",
    name: "Mobile",
    category: "Mobile",
    seller: "AMZ",
    price: 25999,
  },
];
